POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Teste novo repositório",
    "description": "Teste novo repositório",
    "duration": 10
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/40fc2eae-83fb-46f3-bb4e-7af20eace99b
Content-Type: application/json

{
    "title": "Video Node.js",
    "description": "Esse é o vídeo sobre Node.js",
    "duration": 1000
}

###

DELETE http://localhost:3333/videos/40fc2eae-83fb-46f3-bb4e-7af20eace99b