POST https://crud-node-fastify.onrender.com/videos
Content-Type: application/json

{
    "title": "Test Deploy",
    "description": "Test deply on Render",
    "duration": 10
}

###

GET https://crud-node-fastify.onrender.com/videos

###

PUT http://localhost:3333/videos/40fc2eae-83fb-46f3-bb4e-7af20eace99b
Content-Type: application/json

{
    "title": "Video Node.js",
    "description": "Esse é o vídeo sobre Node.js",
    "duration": 1000
}

###

DELETE http://localhost:3333/videos/40fc2eae-83fb-46f3-bb4e-7af20eace99b

###

GET https://localhost:3333/videos