POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Videos javascript",
    "description": "Esse é o quarto vídeo",
    "duration": 360
}

###

GET http://localhost:3333/videos?search=node

###

PUT http://localhost:3333/videos/a1b5f2dd-92eb-47f9-a60b-0428c2b89d09
Content-Type: application/json

{
    "title": "Videos 2",
    "description": "Esse é o segundo vídeo alterado",
    "duration": 360
}

###

DELETE http://localhost:3333/videos/b4091180-b084-4bd5-952e-cf50bed78fa6